services:
  ticketflow:
    container_name: ticketflow
    image: ticketflow:latest
    restart: unless-stopped
    read_only: true
    volumes:
      - ./config:/config:ro
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
